name: Showroom shell Vercel Preview Deployment

on:
  push:
    branches-ignore:
      - main
    paths:
      - 'apps/shell/**'
      - '.github/workflows/shell_vercel_preview_deploy.yaml'

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    environment: 'showroom-shell'
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Add remotes address file to assets
        run: |
          cat << EOF > $HOME/work/showroom/showroom/.vercel/output/static/assets/module-federation.manifest.json
          {
            "fe-mat": "https://showroom-fe-mat.vercel.app/",
            "fe-bs": "https://showroom-fe-bs.vercel.app/"
          }
          EOF

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
